/**
 * Techemy API
 * Techemy
 *
 * OpenAPI spec version: 1
 * Contact: test@test.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface RoleEditDto { 
    id?: number;
    name: string;
    displayName: string;
    description?: string;
    isStatic?: boolean;
}