/**
 * Techemy API
 * Techemy
 *
 * OpenAPI spec version: 1
 * Contact: test@test.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { RoleDto } from './roleDto';

export interface RoleDtoPagedResultDto { 
    items?: Array<RoleDto>;
    totalCount?: number;
}