/**
 * Techemy API
 * Techemy
 *
 * OpenAPI spec version: 1
 * Contact: test@test.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TenantDto } from './tenantDto';

export interface TenantDtoPagedResultDto { 
    items?: Array<TenantDto>;
    totalCount?: number;
}