/**
 * Techemy API
 * Techemy
 *
 * OpenAPI spec version: 1
 * Contact: test@test.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TenantAvailabilityState = 1 | 2 | 3;

export const TenantAvailabilityState = {
    NUMBER_1: 1 as TenantAvailabilityState,
    NUMBER_2: 2 as TenantAvailabilityState,
    NUMBER_3: 3 as TenantAvailabilityState
};